### Incluir los nombres de los colectores en la tabla Persons

Dado que los nombres de colectores fueron insertados en la tabla Occurrences como texto, es necesario generar las entradas homologadas en la tabla Persons y asociar dichas entradas a la tabla Occurrences usando el PersonID. En este sentido, este Notebook es de único uso.

Las homologaciones de las grafías redundantes de nombres de colectores fueron realizadas en LibreOffice Calc y se encuentran en el archivo `collectors.csv`.

In [1]:
from sqlalchemy import create_engine, text
import pandas as pd
import numpy as np
from datetime import datetime

import credentials

In [2]:
conn_str = 'mysql+mysqlconnector://' + \
	f"{credentials.mysql['username']}:{credentials.mysql['password']}" + \
	'@localhost:3306/Mutis'
engine = create_engine(conn_str)
connection = engine.connect()

In [3]:
colls = pd.read_csv("collectors.csv", delimiter="\t")
colls["Standarized_Collector"] = colls.Standarized_Collector.str.replace(".", ". "
	).str.replace(",", ", "
	).str.replace(r"\.\s+,", ".,", regex=True
	).str.replace(r"\s+", " ", regex=True
	).str.replace(r"\s+$|^\s+", "", regex=True
	)

In [51]:
persons = pd.read_sql_table("Persons", connection)

# 1

Si no se han ingresado ningún colector de la tabla a la base de datos, ejecute las siguiente celdas, de lo contrario salte a 2

In [54]:
uniqcolls = colls[
	~colls.Standarized_Collector.isin(persons.NameVerbatim)
	].groupby("Standarized_Collector"
	).size(
	).reset_index(
	).drop(columns=0)

startidx = persons.PersonID.max() + 1
uniqcolls["PersonID"] = uniqcolls.index + startidx
uniqcolls[["LastName", "FirstName"]] = uniqcolls.Standarized_Collector.str.split(
	r",\s+", regex=True, expand=True
	)
uniqcolls[["Abbreviation", "Affiliation", "Email"]] = None, None, None
uniqcolls = uniqcolls.rename(columns={"Standarized_Collector":"NameVerbatim"})
uniqcolls["TimeStamp"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

In [ ]:
# Check no duplicates with records already in db

for row in uniqcolls.itertuples():
	q = persons.loc[persons.LastName == row.LastName]
	if q.shape[0] > 0:
		print(row.NameVerbatim)
		print(persons.loc[persons.LastName == row.LastName, "NameVerbatim"].values)
		print("=" * 40)

Barbosa, O.
['Barbosa, C.']
========================================
Betancur, A.
['Betancur, Julio']
========================================
Castellanos, J. D.
['Castellanos, C.']
========================================
Cuellar, Y.
['Cuellar, D. M.']
========================================
Daniel, R.
['Daniel, H.']
========================================
Escobar, W.
['Escobar, L. K.']
========================================
Gamboa, C.
['Gamboa, M. A.']
========================================
Gamboa, M. C.
['Gamboa, M. A.']
========================================
García, A.
['García, Y.']
========================================
García, B.
['García, Y.']
========================================
García, C.
['García, Y.']
========================================
García, F.
['García, Y.']
========================================
García, G.
['García, Y.']
========================================
García, H.
['García, Y.']
========================================
García, L. A. de
['García, Y.']
========================================
García, M.
['García, Y.']
========================================
García, M. C.
['García, Y.']
========================================
García, N.
['García, Y.']
========================================
García, Ni.
['García, Y.']
========================================
García, R.
['García, Y.']
========================================
García, Roger Fabián
['García, Y.']
========================================
García, Yamile
['García, Y.']
========================================
Gil, C. E.
['Gil, E.']
========================================
Hernández, G.
['Hernández, A.']
========================================
Hernández, J.
['Hernández, A.']
========================================
Hernández, L.
['Hernández, A.']
========================================
Hernández, M.
['Hernández, A.']
========================================
Hernández, N.
['Hernández, A.']
========================================
Hernández, Nicolás
['Hernández, A.']
========================================
Lewis, W. H.
['Lewis, G. P.']
========================================
Mayorga, C.
['Mayorga, M.' 'Mayorga, N. C.']
========================================
Montenegro, A.
['Montenegro, P. A.']
========================================
Montenegro, E.
['Montenegro, P. A.']
========================================
Montenegro, Leyla
['Montenegro, P. A.']
========================================
Montenegro, O.
['Montenegro, P. A.']
========================================
Parrado, E.
['Parrado, C.']
========================================
Pedraza-Peñalosa, Carlos
['Pedraza-Peñalosa, Paola']
========================================
Pérez, B.
['Pérez, G.' 'Pérez, M. R.']
========================================
Pérez, Darío
['Pérez, G.' 'Pérez, M. R.']
========================================
Pérez, J.
['Pérez, G.' 'Pérez, M. R.']
========================================
Pérez, S.
['Pérez, G.' 'Pérez, M. R.']
========================================
Pérez-Suárez, Verónica
['Pérez-Suárez, B.']
========================================
Rojas, A.
['Rojas, C.']
========================================
Rojas, J. M.
['Rojas, C.']
========================================
Rojas, M.
['Rojas, C.']
========================================
Rojas, N. C.
['Rojas, C.']
========================================
Schneider, A.
['Schneider, M.']
========================================
Smith, S. G
['Smith, A. C.' 'Smith, L. B.']
========================================
Sosa, R.
['Sosa, V.']
========================================
Sánchez, A.
['Sánchez, M. G.']
========================================
Sánchez, D.
['Sánchez, M. G.']
========================================
Sánchez, G.
['Sánchez, M. G.']
========================================
Sánchez, L.
['Sánchez, M. G.']
========================================
Sánchez, M. C.
['Sánchez, M. G.']
========================================
Sánchez, P.
['Sánchez, M. G.']
========================================
Sánchez, Roberto
['Sánchez, M. G.']
========================================
Sánchez, V.
['Sánchez, M. G.']
========================================
Sánchez, Y.
['Sánchez, M. G.']
========================================
Torres, F.
['Torres, M. P.']
========================================
Torres, H.
['Torres, M. P.']
========================================
Torres, J. M.
['Torres, M. P.']
========================================
Torres, T.
['Torres, M. P.']
========================================
Vega, G.
['Vega, I. S.' 'Vega, N.']
========================================
Vega, W.
['Vega, I. S.' 'Vega, N.']
========================================
Velásquez
['Velásquez, C.']
========================================
Velásquez, A.
['Velásquez, C.']
========================================
Velásquez, G.
['Velásquez, C.']
========================================
Velásquez, R.
['Velásquez, C.']
========================================
Velásquez, S.
['Velásquez, C.']
========================================
Velásquez, T.
['Velásquez, C.']
========================================
Williams, Ll.
['Williams, L. O.']
========================================

In [57]:
uniqcolls[persons.columns].to_sql('Persons', engine, if_exists='append', index=False, 
		chunksize=10000, method='multi'
	)

1193

# 2

Se obtienen los PersonID de la BD Mutis que corresponden a todos los colectores verbatim de la tabla ocurrencias.

In [4]:
persons = pd.read_sql_table("Persons", connection)

In [ ]:
# Just to check there aren't missing PersonIDs in the original set of collector names

print(
colls.merge(
	persons[["NameVerbatim", "PersonID"]],
	left_on="Standarized_Collector",
	right_on="NameVerbatim",
	how="left"
).to_string()
)

                              CollectorVerbatim                      Standarized_Collector                               NameVerbatim  PersonID
0                                     Acero, E.                             Acero, Enrique                             Acero, Enrique       171
1                                   Acero, J.D.                               Acero, J. D.                               Acero, J. D.       172
2                            Acevedo-Luna, N.I.                        Acevedo-Luna, N. I.                        Acevedo-Luna, N. I.       175
3                                Acevedo, E. de                             Acevedo, E. de                             Acevedo, E. de       173
4                                   Acevedo, O.                                Acevedo, O.                                Acevedo, O.       174
5                          Acosta-Arteaga, C.E.                      Acosta-Arteaga, C. E.                      Acosta-Arteaga, C. E.       179
6                          Acosta-Ortiz, Mónica                       Acosta-Ortiz, Mónica                       Acosta-Ortiz, Mónica       180
7                                    Acosta, D.                                 Acosta, D.                                 Acosta, D.       176
8                                  Acosta, M.A.                              Acosta, M. A.                              Acosta, M. A.       177
9                                  Acosta, M.G.                              Acosta, M. G.                              Acosta, M. G.       178
10                            Acuña-Donatto, H.                          Acuña-Donatto, H.                          Acuña-Donatto, H.       181
11                                    Adame, J.                                  Adame, J.                                  Adame, J.       182
12                               Adarme, M.L.D.                           Adarme, M. L. D.                           Adarme, M. L. D.       183
13                                      Adriana                                    Adriana                                    Adriana       184
14                                 Afanador, S.                               Afanador, S.                               Afanador, S.       185
15                                  Agudelo, M.                                Agudelo, M.                                Agudelo, M.       186
16                             Aguirre-G., L.E.                          Aguirre-G., L. E.                          Aguirre-G., L. E.       189
17                                  Aguirre, C.                                Aguirre, C.                                Aguirre, C.       187
18                                  Aguirre, H.                                Aguirre, H.                                Aguirre, H.       188
19                             Aguirrezabal, I.                           Aguirrezabal, I.                           Aguirrezabal, I.       190
20                                  Alarcón, G.                                Alarcón, G.                                Alarcón, G.       191
21                                  Alarcón, N.                                Alarcón, N.                                Alarcón, N.       192
22                               Albarracín, A.                             Albarracín, A.                             Albarracín, A.       193
23                                      Alberto                                    Alberto                                    Alberto       195
24                                Albesiano, S.                           Albeciano, Sofía                           Albeciano, Sofía       194
25                             Alfonso-Cano, A.                           Alfonso-Cano, A.                           Alfonso-Cano, A.       198
26                                  Alfonso, R.                                Alfonso, R.                                Alfonso, R.       196
27                                Alfonso, René                              Alfonso, René                              Alfonso, René       197
28                                  Allen, P.H.                               Allen, P. H.                               Allen, P. H.       199
29                                  Alomoto, V.                                Alomoto, V.                                Alomoto, V.       200
30                                   Alonso, F.                                 Alonso, F.                                 Alonso, F.       201
31                                   Alonso, N.                                 Alonso, N.                                 Alonso, N.       202
32                                      Alromar                                    Alromar                                    Alromar       203
33                               Alston, A.H.G.                           Alston, A. H. G.                           Alston, A. H. G.       204
34                                      Alumnos                                    Alumnos                                    Alumnos       205
35                Alumnos Instituto de La Salle                           Alumnos La Salle                           Alumnos La Salle       206
36                       Alumnos Liceo La Salle                           Alumnos La Salle                           Alumnos La Salle       206
37                             Alumnos U. Salle                           Alumnos La Salle                           Alumnos La Salle       206
38                                Álvarez, C.G.                             Álvarez, C. G.                             Álvarez, C. G.      1357
39                                  Álvarez, F.                                Álvarez, F.                                Álvarez, F.      1358
40                                  Álvarez, M.                                Álvarez, M.                                Álvarez, M.      1359
41                                Alvear-P., M.                    Alvear-Pacheco, Marcela                    Alvear-Pacheco, Marcela       207
42                                   Alzate, L.                                 Alzate, L.                                 Alzate, L.       208
43                                    Amaya, J.                                  Amaya, J.                                  Amaya, J.       209
44                              Amortegui, B.G.                           Amortegui, B. G.                           Amortegui, B. G.       210
45                             Andrade, Liliana                           Andrade, Liliana                           Andrade, Liliana       211
46                                    André, É.                                  André, É.                                  André, É.       212
47                                 Ángel-R., M.                               Ángel-R., M.                               Ángel-R., M.      1360
48                                    Angel, F.                                  Angel, F.                                  Angel, F.       213
49                                   Angulo, A.                                 Angulo, A.                                 Angulo, A.       214
50                                      Anónimo                                    Anónimo                                    Anónimo       219
51                              Antolínez, A.R.                           Antolínez, A. R.                           Antolínez, A. R.       215
52                                    Anton, G.                                Antonio, G.                                Antonio, G.       216
53                                  Antonio, G.                                Antonio, G.                                Antonio, G.       216
54                                   Anzola, F.                                 Anzola, F.                                 Anzola, F.       217
55                              Anzola, Nicolás                            Anzola, Nicolás                            Anzola, Nicolás       218
56                                 Aparicio, R.                               Aparicio, R.                               Aparicio, R.       220
57                                   Aponte, M.                                 Aponte, M.                                 Aponte, M.       221
58                                     Arai, K.                                   Arai, K.                                   Arai, K.       222
59                                 Aranda, J.N.                              Aranda, J. N.                              Aranda, J. N.       223
60                                   Arango, A.                                 Arango, A.                                 Arango, A.       224
61                                   Arango, D.                              Arango, G. D.                              Arango, G. D.       225
62                                 Arango, G.D.                              Arango, G. D.                              Arango, G. D.       225
63                                Araque-M., J.                          Araque-Molina, J.                          Araque-Molina, J.       226
64                            Araque-Molina, J.                          Araque-Molina, J.                          Araque-Molina, J.       226
65                              Arboleda-R., A.                            Arboleda-R., A.                            Arboleda-R., A.       227
66                         Arcadio-Quintero, E.                       Arcadio-Quintero, E.                       Arcadio-Quintero, E.       228
67                                   Arenas, C.                                 Arenas, C.                                 Arenas, C.       229
68                                 Arenas, M.S.                              Arenas, M. S.                              Arenas, M. S.       230
69                          Arévalo-Marín, Edna                        Arévalo-Marín, Edna                        Arévalo-Marín, Edna       244
70                                  Arévalo, A.                                Arévalo, A.                                Arévalo, A.       242
71                                Arévalo, L.E.                             Arévalo, L. E.                             Arévalo, L. E.       243
72                                    Arias, A.                                  Arias, A.                                  Arias, A.       231
73                                    Arias, H.                                  Arias, H.                                  Arias, H.       232
74                                  Arias, M.A.                               Arias, M. A.                               Arias, M. A.       233
75                                    Arias, O.                                  Arias, O.                                  Arias, O.       234
76                                 Aristide, L.                               Aristide, L.                               Aristide, L.         7
77                                    Ariza, C.                                  Ariza, C.                                  Ariza, C.       235
78                                    Ariza, S.                                  Ariza, S.                                  Ariza, S.       236
79                                    Ariza, W.                             Ariza, William                             Ariza, William       237
80                                  Arrieta, R.                                Arrieta, R.                                Arrieta, R.       238
81                                   Arsene, F.                                 Arsene, F.                                 Arsene, F.       239
82                            Arteaga de G., L.                          Arteaga de G., L.                          Arteaga de G., L.       240
83                                  Arteaga, M.                                Arteaga, M.                                Arteaga, M.       241
84                                   Avella, M.                                 Avella, M.                                 Avella, M.       245
85                                    Ávila, F.                        Ávila, Fabio Andrés                        Ávila, Fabio Andrés      1361
86                                    Ávila, M.                                  Ávila, M.                                  Ávila, M.      1362
87                                    Ávila, Y.                                  Ávila, Y.                                  Ávila, Y.      1363
88                                   Aviles, H.                                 Aviles, H.                                 Aviles, H.       246
89                                 Azabache, L.                               Azabache, L.                               Azabache, L.       247
90                                     Báez, A.                                   Báez, A.                                   Báez, A.       335
91                              Ballesteros, F.                            Ballesteros, F.                            Ballesteros, F.       248
92                              Ballesteros, O.                            Ballesteros, O.                            Ballesteros, O.       249
93                                  Balls, E.K.                               Balls, E. K.                               Balls, E. K.       250
94                                 Baptiste, H.                               Baptiste, H.                               Baptiste, H.       251
95                                 Baptiste, I.                               Baptiste, I.                               Baptiste, I.       252
96                               Baptiste, M.P.                            Baptiste, M. P.                            Baptiste, M. P.       253
97                                Baquero, M.P.                             Baquero, M. P.                             Baquero, M. P.       254
98                                  Barajas, P.                                Barajas, P.                                Barajas, P.       255
99                            Barbosa-Parra, A.                          Barbosa-Parra, A.                          Barbosa-Parra, A.       257
100                                 Barbosa, C.                                Barbosa, C.                                Barbosa, C.         9
101                                 Barbosa, O.                                Barbosa, O.                                Barbosa, O.       256
102                                 Barclay, A.                    Barclay, Arthur Stewart                    Barclay, Arthur Stewart       258
103                               Barclay, A.S.                    Barclay, Arthur Stewart                    Barclay, Arthur Stewart       258
104                               Barclay, H.G.                    Barclay, Harriet George                    Barclay, Harriet George       259
105                                 Baresch, A.                                Baresch, A.                                Baresch, A.       260
106                            Barkley-W., F.A.                          Barkley-W., F. A.                          Barkley-W., F. A.       261
107                                 Barkley, F.                          Barkley-W., F. A.                          Barkley-W., F. A.       261
108                        Barragán-Fonseca, K.                       Barragán-Fonseca, K.                       Barragán-Fonseca, K.       263
109                                Barragán, K.                       Barragán-Fonseca, K.                       Barragán-Fonseca, K.       263
110                                Barragán, L.                               Barragán, L.                               Barragán, L.       262
111                             Barrenechea, M.                            Barrenechea, M.                            Barrenechea, M.       264
112                                 Barrera, D.                                Barrera, D.                                Barrera, D.       265
113                             Barrera, Germán                            Barrera, Germán                            Barrera, Germán       266
114                                 Barrera, I.                      Barrera, José Ignacio                      Barrera, José Ignacio       268
115                            Barrera, Ignacio                      Barrera, José Ignacio                      Barrera, José Ignacio       268
116                               Barrera, J.L.                             Barrera, J. L.                             Barrera, J. L.       267
117                       Barrera, José Ignacio                      Barrera, José Ignacio                      Barrera, José Ignacio       268
118                                 Barrera, L.                             Barrera, L. A.                             Barrera, L. A.       269
119                               Barrera, L.A.                             Barrera, L. A.                             Barrera, L. A.       269
120                                 Barrera, M.                                Barrera, M.                                Barrera, M.       270
121                              Barreto-P., A.                             Barreto-P., A.                             Barreto-P., A.       271
122                                 Barriga, R.                                Barriga, R.                                Barriga, R.       272
123                            Barrington, D.S.                          Barrington, D. S.                          Barrington, D. S.       273
124                                  Barros, R.                                 Barros, R.                                 Barros, R.       274
125                            Baruffol, Martín                           Baruffol, Martín                           Baruffol, Martín       275
126                                Bautista, L.                               Bautista, L.                               Bautista, L.       276
127                                   Bayón, R.                                  Bayón, R.                                  Bayón, R.       277
128                                 Becerra, J.                                Becerra, J.                                Becerra, J.       278
129                               Becerra, R.B.                             Becerra, R. B.                             Becerra, R. B.       279
130                                Bejarano, M.                            Bejarano, M. V.                            Bejarano, M. V.       280
131                              Bejarano, M.V.                            Bejarano, M. V.                            Bejarano, M. V.       280
132                                Bejarano, O.                               Bejarano, O.                               Bejarano, O.       281
133                                   Bello, M.                               Bello, M. A.                               Bello, M. A.       282
134                                 Bello, M.A.                               Bello, M. A.                               Bello, M. A.       282
135                                 Bello, M.L.                               Bello, M. L.                               Bello, M. L.       283
136                                 Beltrán, F.                                Beltrán, F.                                Beltrán, F.       284

In [229]:
peoper = pd.read_sql_table("PeoplePersons", connection)

In [230]:
people = pd.read_sql_table("People", connection)

In [225]:
maxper = startidx - 1
maxpeople = people.PeopleID.max()

In [226]:
maxper, maxpeople

(170, 153)

In [227]:
# The following works because all collectors are one-person teams
peopleid = maxpeople

for perid in persons.PersonID[persons.PersonID > maxper]:
	peopleid += 1

	s = text("INSERT INTO People(PeopleID) VALUES (:ppid)")
	connection.execute(s, {"ppid": peopleid})
	connection.commit()

	s = text("INSERT INTO PeoplePersons VALUES (:ppid, :perid, 1, '2026-02-16')")
	connection.execute(s, {"ppid": peopleid, "perid": perid})
	connection.commit()

In [234]:
occcolls = pd.read_sql_query("SELECT CollectorVerbatim, Collector FROM Occurrences WHERE CollectorVerbatim IS NOT NULL", connection)

In [238]:
colls

,CollectorVerbatim,NameVerbatim,LastName,FirstName,PersonID,Abbreviation,Affiliation,Email,TimeStamp
0,"Acero, E.","Acero, Enrique",Acero,Enrique,171,None,None,None,2026-02-16
1,"Acero, J.D.","Acero, J. D.",Acero,J. D.,172,None,None,None,2026-02-16
2,"Acevedo-Luna, N.I.","Acevedo-Luna, N. I.",Acevedo-Luna,N. I.,173,None,None,None,2026-02-16
3,"Acevedo, E. de","Acevedo, E. de",Acevedo,E. de,174,None,None,None,2026-02-16
4,"Acevedo, O.","Acevedo, O.",Acevedo,O.,175,None,None,None,2026-02-16
...,...,...,...,...,...,...,...,...,...
1325,"Zucolotto, S.","Zucolotto, S.",Zucolotto,S.,1496,None,None,None,2026-02-16
1326,"Zuluaga-C., Juliana","Zuluaga-C., Juliana",Zuluaga-C.,Juliana,1497,None,None,None,2026-02-16
1327,"Zuluaga-R., S.","Zuluaga-R., S.",Zuluaga-R.,S.,1498,None,None,None,2026-02-16
1328,"Zulueta, I. de","Zulueta, I. de",Zulueta,I. de,1499,None,None,None,2026-02-16
1329,"Zúñiga, A.M.","Zúñiga, A. M.",Zúñiga,A. M.,1500,None,None,None,2026-02-16

In [237]:
persons[persons.NameVerbatim.str.startswith('Acero')]

,PersonID,NameVerbatim,FirstName,LastName,Abbreviation,Affiliation,Email,TimeStamp
170,171,"Acero, Enrique",Enrique,Acero,None,None,None,2026-02-16
171,172,"Acero, J. D.",J. D.,Acero,None,None,None,2026-02-16

In [232]:
people

      PeopleID           TimeStamp
0            1 2025-06-18 09:15:52
1            2 2025-06-18 09:15:52
2            3 2025-06-18 09:16:06
3            4 2025-06-18 09:16:06
4            5 2025-06-18 09:16:06
...        ...                 ...
1478      1479 2026-02-16 20:17:50
1479      1480 2026-02-16 20:17:50
1480      1481 2026-02-16 20:17:50
1481      1482 2026-02-16 20:17:50
1482      1483 2026-02-16 20:17:50

[1483 rows x 2 columns]

In [246]:
colls[colls.NameVerbatim == "Lancheros, Héctor Orlando"]

,CollectorVerbatim,NameVerbatim,LastName,FirstName,PersonID,Abbreviation,Affiliation,Email,TimeStamp
677,"Lancheros, H.","Lancheros, Héctor Orlando",Lancheros,Héctor Orlando,848,None,None,None,2026-02-16
678,"Lancheros, Héctor O.","Lancheros, Héctor Orlando",Lancheros,Héctor Orlando,849,None,None,None,2026-02-16
679,"Lancheros, Héctor Orlando","Lancheros, Héctor Orlando",Lancheros,Héctor Orlando,850,None,None,None,2026-02-16

In [244]:
for row in occcolls.itertuples():

	if pd.isna(row.Collector):

		try:

			stdcoll = colls.loc[
				colls.CollectorVerbatim == row.CollectorVerbatim,
				"NameVerbatim"].item()


			perid = persons.loc[
				persons.NameVerbatim == stdcoll, 
				"PersonID"
				].item()
			
		except:
			#print(f"{perid=}")
			print(f"{row.CollectorVerbatim=}")
			print(f"{stdcoll=}")
			continue

		peopleid = peoper.loc[
			(peoper.Person == perid),# & (peoper.Order == 1), 
			"People"].item()

		#print(f"{perid=}, {peopleid=}")

		s = text("SELECT OccurrenceID FROM Occurrences where CollectorVerbatim = :thcoll")
		thoccs = connection.execute(s, {"thcoll": row.CollectorVerbatim}).fetchall()

		#print(f"{thoccs}")

		#for i in (x[0] for x in thoccs):

		#	s = text("UPDATE Occurrences SET Collector = :ppid WHERE OccurrenceID = :occid")
		#	connection.execute(s, {"ppid": peopleid, "occid": i})
		#	connection.commit()

		#break

row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Instituto de La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Liceo La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos Liceo La Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos U. Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos U. Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos U. Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos U. Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos U. Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos U. Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos U. Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos U. Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos U. Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos U. Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Alumnos U. Salle'
stdcoll='Alumnos La Salle'
row.CollectorVerbatim='Anton, G.'
stdcoll='Antonio, G.'
row.CollectorVerbatim='Antonio, G.'
stdcoll='Antonio, G.'
row.CollectorVerbatim='Antonio, G.'
stdcoll='Antonio, G.'
row.CollectorVerbatim='Arango, D.'
stdcoll='Arango, G. D.'
row.CollectorVerbatim='Arango, D.'
stdcoll='Arango, G. D.'
row.CollectorVerbatim='Arango, D.'
stdcoll='Arango, G. D.'
row.CollectorVerbatim='Arango, G.D.'
stdcoll='Arango, G. D.'
row.CollectorVerbatim='Arango, G.D.'
stdcoll='Arango, G. D.'
row.CollectorVerbatim='Arango, G.D.'
stdcoll='Arango, G. D.'
row.CollectorVerbatim='Araque-M., J.'
stdcoll='Araque-Molina, J.'
row.CollectorVerbatim='Araque-M., J.'
stdcoll='Araque-Molina, J.'
row.CollectorVerbatim='Araque-M., J.'
stdcoll='Araque-Molina, J.'
row.CollectorVerbatim='Araque-M., J.'
stdcoll='Araque-Molina, J.'
row.CollectorVerbatim='Araque-M., J.'
stdcoll='Araque-Molina, J.'
row.CollectorVerbatim='Araque-M., J.'
stdcoll='Araque-Molina, J.'
row.CollectorVerbatim='Araque-Molina, J.'
stdcoll='Araque-Molina, J.'
row.CollectorVerbatim='Araque-Molina, J.'
stdcoll='Araque-Molina, J.'
row.CollectorVerbatim='Aristide, L.'
stdcoll='Arias, O.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barbosa, C.'
stdcoll='Barajas, P.'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barclay, A.S.'
stdcoll='Barclay, Arthur Stewart'
row.CollectorVerbatim='Barkley, F.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'
row.CollectorVerbatim='Barkley-W., F.A.'
stdcoll='Barkley-W., F. A.'

KeyboardInterrupt:

In [149]:
colls.loc[colls.NameVerbatim == collector, "CollectorVerbatim"].item()

'Acero, E.'

In [223]:
connection.close()